import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import LOGIN from '../components/login'
import REGISTER from '../components/register'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lotto Analysis - Florida</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href={'/login'}>
          Login
        </Link> <br />
        <Link href={'/register'}>
          Register
        </Link>
        {/* <LOGIN /> */}
      </main>
    </div>
  )
}
