import Head from 'next/head'

import REGISTER from '../components/register'

function register() {
    return (
        <div>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <REGISTER />
        </div>
    )
}

export default register